In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as img
import numpy as np
from scipy.misc import imresize

%matplotlib inline

import os
from os import listdir
from os.path import isfile, join
import shutil
import stat
import collections
from collections import defaultdict
import matplotlib.image as mpimg 

from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets

import h5py
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
test = pd.read_csv("test.csv")
label = test['cuisine']
feature = test['ingredients']
x_test = feature
y_test = label

#need to run the above code after training

In [3]:
df = pd.read_csv("train.csv",low_memory=False)
df['label'] = 'train'
label = df['cuisine']
feature = df['ingredients']
x_train = feature
y_train = label

In [4]:
data = df.values
#y is label
y = data [:,0]
#x is feature
x = data [:, 2]
#print(y)

In [5]:
from sklearn.preprocessing import LabelEncoder

# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

In [6]:
label_encoder.fit(x)
encoded_x = label_encoder.transform(x)
#encoded_x

In [7]:
from keras.utils import to_categorical
one_hot_y = to_categorical(encoded_y)
one_hot_y

Using TensorFlow backend.


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [8]:
one_hot_x = to_categorical(encoded_x)
one_hot_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [9]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
#clf.fit(one_hot_x,one_hot_y)

In [10]:
#for test data one-hot encoding
data1 = test.values
#y is label
y1 = data1 [:,0]
#x is feature
x1 = data1 [:, 2]

In [11]:

label_encoder.fit(y1)
encoded_y1 = label_encoder.transform(y1)

In [12]:
label_encoder.fit(x1)
encoded_x1 = label_encoder.transform(x1)

In [13]:
one_hot_y1 = to_categorical(encoded_y1)
one_hot_y1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [20]:
one_hot_x1 = to_categorical(encoded_x1)
#one_hot_x1

MemoryError: 

In [17]:
one_hot_x1_df = pd.DataFrame(one_hot_x1)
one_hot_x1_df['label'] = 'test'
one_hot_x_df = pd.DataFrame(one_hot_x)
one_hot_x_df['label'] = 'train'
concat_df = pd.concat([one_hot_x_df , one_hot_x1_df],sort = False)
features_df = pd.get_dummies(concat_df).fillna(0)
features_df

NameError: name 'one_hot_x1' is not defined

In [ ]:
train_df = features_df[features_df['label_train'] == 1]

test_df = features_df[features_df['label_test'] == 1]
test_df.columns

In [ ]:
train_df = train_df.drop(['label_test','label_train'],axis = 1)
#test_df = test_df.drop(['label_test','label_train'], axis=1)
#test_df.columns



In [ ]:
train_df.columns

In [ ]:
test_df = test_df.drop(['label_test','label_train'],axis = 1)

In [ ]:
test_df

In [ ]:
clf.fit(train_df,one_hot_y)

In [ ]:
train_df.columns

In [ ]:
y_pred=clf.predict(test_df)

In [ ]:
from sklearn import metrics

In [ ]:
print("Accuracy:",metrics.accuracy_score(one_hot_y1, y_pred))